<?php

$class_lesson_name =[
        '5'=>'5.Sınıf',
        '6'=>'6.Sınıf',
        '7'=>'7.Sınıf',
        '8'=>'8.Sınıf',
        '9'=>'9.Sınıf',
//        '10'=>'10.Sınıf',
//        '11'=>'11.Sınıf',
//        '12'=>'12.Sınıf',
        '50'=>'Fen Lisesi 9.Sınıf',
//        '51'=>'Fen Lisesi 10.Sınıf',
//        '52'=>'Fen Lisesi 11.Sınıf',
//        '53'=>'Fen Lisesi 12.Sınıf',
        '80'=>'KPSS',
        '81'=>'KPSS + EĞİTİM'
];

if (session('user_class') <= 8){
    $lessons_table_name = 'lessons_lgs';
} elseif (session('user_class') == 9 || session('user_class') == 50){
    $lessons_table_name = 'lessons_nine';
} elseif (session('user_class') == 10 || session('user_class') == 51){
    $lessons_table_name = 'lessons_ten';
} elseif (session('user_class') == 11 || session('user_class') == 52){
    $lessons_table_name = 'lessons_eleven';
} elseif (session('user_class') == 12 || session('user_class') == 53){
    $lessons_table_name = 'lessons_twelve';
} elseif (session('user_class') == 80){
    $lessons_table_name = 'lessons_kpss';
} elseif (session('user_class') == 81){
    $lessons_table_name = 'lessons_kpss_education';
}


$_lessons = [];
$_lectures = [];

if (session('user_class') <= 8) {

    $lesson_zero=[
        'math' => 0,
        'turkish' => 0,
        'science' => 0,
        'history' => 0,
        'english' => 0,
        'religion' => 0
    ];

    $_lessons = [
        'math' => 'Matematik',
        'turkish' => 'Türkçe',
        'science' => 'Fen ve Teknoloji',
        'history' => 'T.C. İnkılap Tarihi',
        'english' => 'İngilizce',
        'religion' => 'Din Kültürü'
    ];

    $_lectures = [

        'math' => [
            'Çarpanlar ve Katlar',
            'Üslü İfadeler',
            'Kareköklü İfadeler',
            'Veri Analizi',
            'Basit Olayların Olma Olasılığı',
            'Cebirsel İfadeler ve Özdeşlikler',
            'Doğrusal Denklemler',
            'Eşitsizlikler',
            'Üçgenler',
            'Eşlik ve Benzerlik',
            'Dönüşüm Geometrisi',
            'Geometrik Cisimler',
            'Diğer Konular'
        ],
        'turkish' => [
            'Fiilimsiler',
            'Sözcükte Anlam',
            'Söz Gruplarında Anlam',
            'Deyimler ve Atasözleri',
            'Cümlenin Öğeleri',
            'Söz Sanatları',
            'Yazım Kuralları',
            'Noktalama İşaretleri',
            'Cümlede Anlam',
            'Metin Türleri',
            'Cümle Türleri',
            'Parçada Anlam',
            'Fiilde Çatı',
            'Cümlede Anlam',
            'Görsel Okuma',
            'Yazım Kuralları',
            'Noktalama İşaretleri',
            'Anlatım Bozuklukları',
            'Diğer Konular'
        ],
        'science' => [
            'Mevsimler ve İklim / Dünya ve Evren',
            'DNA ve Genetik Kod / Canlılar ve Yaşam',
            'Basınç / Fiziksel Olaylar',
            'Madde ve Endüstri / Madde ve Doğası',
            'Basit Makineler / Fiziksel Olaylar',
            'Enerji Dönüşümleri ve Çevre Bilimi',
            'Elektrik Yükleri ve Elektrik Enerjisi / Fiziksel Olaylar',
            'Diğer Konular'
        ],
        'history' => [
            'Bi̇r Kahraman Doğuyor',
            'Mi̇llî Uyaniş',
            'Mi̇llî Bi̇r Destan',
            'Atatürkçülük Ve Çağdaşlaşan Türki̇ye',
            'Demokrati̇kleşme Çabalari',
            'Atatürk Dönemi̇ Türk Diş Poli̇ti̇kasi',
            'Atatürk’ün Ölümü Ve Sonrasi',
            'Diğer Konular'
        ],
        'religion' => [
            'Kader İnanci',
            'Zekât Ve Sadaka',
            'Di̇n Ve Hayat',
            'Hz. Muhammed’i̇n Örnekli̇ği̇',
            'Kur’an-i Keri̇m Ve Özelli̇kleri̇',
            'Diğer Konular'
        ],
        'english' => [
            'Friendship',
            'Teen Life',
            'Cooking',
            'Communıcation',
            'The Internet',
            'Adventures',
            'Tourısm',
            'Chores',
            'Science',
            'Natural Forces',
            'Diğer Konular'
        ]
    ];

} elseif (session('user_class') == 9) {

    $lesson_zero=[
        'math' => 0,
        'turkish_l_l' => 0,
        'history' => 0,
        'religion' => 0,
        'geography' => 0,
        'physics' => 0,
        'chemistry' => 0,
        'biology' => 0,
        'f_language_1' => 0,
        'f_language_2' => 0,
    ];

    $_lessons = [
        'math' => 'Matematik',
        'turkish_l_l' => 'Türk Dili ve Edebiyatı',
        'history' => 'Tarih',
        'religion' => 'Din Kültürü ve Ahlak Bilgisi',
        'geography' => 'Coğrafya',
        'physics' => 'Fizik',
        'chemistry' => 'Kimya',
        'biology' => 'Biyoloji',
        'f_language_1' => '1. Yabancı Dil',
        'f_language_2' => '2. Yabancı Dil',
    ];

    $_lectures = [
        'math' => [
            'Mantık',
            'Kümeler',
            'Denklem ve Eşitsizlikler',
            'Denklem ve Eşitsizlikler ile İlgili Uygulamalar',
            'Üçgenlerde Temel Kavramlar',
            'Üçgenlerde Eşlik ve Benzerlik',
            'Üçgenin Yardımcı Elemanları',
            'Dik Üçgen ve Trigonometri',
            'Üçgenin Alanı',
            'Veri',
        ],
        'turkish_l_l' => [
            'Yazım Kuralları',
            'Noktalama İşaretleri',
            'İsim',
            'Sıfat',
            'Dinleme Türleri ve Etkili Dinlemenin İlkeleri',
            'Edat',
            'Bağlaç',
            'Ünlem',
            'Zamir',
            'Zarf',
            'Fiil',
            'CV / Öz Geçmiş',
            'İletişim ve Dil',
            'Hikaye',
            'Şiir',
            'Masal/Fabl',
            'Roman',
            'Tiyatro',
            'Biyografi / Otobiyografi',
        ],
        'history' => [
            'Tarih ve Zaman',
            'İnsanlığın İlk Dönemleri',
            'Orta Çağ’da Dünya',
            'İlk ve Orta Çağlarda Türk Dünyası',
            'İslam Medeniyetinin Doğuşu',
            'Türklerin İslamiyeti Kabulü',
            'İlk Türk İslam Devletleri',
        ],
        'religion' => [
            'Din Kültürü ve Ahlak Bilgisi',
        ],
        'geography' => [
            'Doğa ve İnsan Etkileşimi',
            'Coğrafyanın Bölümleri',
            'Coğrafyanın Tarihi Gelişimi',
            'Coğrafyanın İlkeleri',
            'Coğrafyanın Yararlandığı Bilim Dalları',
            'Dünya’nın Şekli ve Sonuçları',
            'Dünya’nın Günlük Hareketi ve Sonuçları',
            'Dünya’nın Yıllık Hareketi ve Sonuçları',
            'Paralel ve Meridyenler',
            'Koordinat Sistemi',
            'Mutlak ve Göreceli Konum',
            'Türkiye’nin Özel Konumu ve Sonuçları',
            'Türkiye’nin Matematik Konumu ve Sonuçları',
            'Harita Bilgisi',
            'İzohips Haritası',
            'Atmosfer',
            'Hava Durumu ve İklim',
            'Sıcaklık',
            'Basınç ve Rüzgarlar',
            'Nem ve Yağış',
            'Yeryüzündeki İklim Tipleri',
            'Türkiye’nin İklimini Etkileyen Faktörler',
            'Türkiye’de İklim Elemanları',
            'Türkiye’de Görülen İklim Tipleri',
            'Yerleşmelerin Gelişimi',
            'Yerleşme Doku Ve Tipleri',
            'Türkiye’de Yerleşmelerin Gelişimi ve Fonksiyonel Özellikleri',
            'Türkiye’den ve Dünya’dan Bölge türleri',
            'İnsanların Doğal Çevreyi Kullanma Biçimler',
        ],
        'physics' => [
            'Fizik Bilimine Giriş',
            'Madde ve Özellikleri',
            'Hareket ve Kuvvet',
            'Enerji',
            'Isı ve Sıcaklık',
            'Elektrostatik',
        ],
        'chemistry' => [
            'Simyadan Kimya',
            'Kimya Disiplinleri',
            'Kimyacıların Çalışma Alanları',
            'Kimyanın Sembolik Dili',
            'Kimya Uygulamalarında İş Sağlığı ve Güvenliği',
            'Atom Modelleri',
            'Atomun Yapısı',
            'Periyodik Sitem',
            'Kimyasal Tür',
            'Güçlü Etkileşimler',
            'Zayıf Etkileşimler',
            'Fiziksel ve Kimyasal Değişimler',
            'Maddenin Fiziksel Halleri',
            'Katılar',
            'Sıvılar',
            'Gazlar',
            'Plazma',
            'Su ve Hayat',
            'Çevre Kimyası',
        ],
        'biology' => [
            'Biyoloji ve Canlıların Ortak Özellikleri',
            'Canlıların Yapısında Bulunan Temel Bileşikler',
            'Hücre',
            'Canlıların Çeşitliliği ve Sınıflandırılması',
            'Canlı Alemleri ve Özellikleri',
        ],
        'f_language_1' => [
            'Studying Abroad',
            'My Environment',
            'Movies',
            'Human in Nature',
            'Inspirational People',
            'Bridging Cultures',
            'World Heritage',
            'Emergency and Health Problems',
            'Invitations and Celebrations',
            'Television and Social Media',
        ],
        'f_language_2' => [
            'Almanca',
            'Fransızca'
        ],
    ];

} elseif (session('user_class') == 10) {

    $lesson_zero=[
        'math' => 0,
        'turkish_l_l' => 0,
        'history' => 0,
        'religion' => 0,
        'geography' => 0,
        'physics' => 0,
        'chemistry' => 0,
        'biology' => 0,
        'f_language_1' => 0,
        'f_language_2' => 0,
    ];

    $_lessons = [
        'math' => 'Matematik',
        'turkish_l_l' => 'Türk Dili ve Edebiyatı',
        'history' => 'Tarih',
        'religion' => 'Din Kültürü ve Ahlak Bilgisi',
        'geography' => 'Coğrafya',
        'physics' => 'Fizik',
        'chemistry' => 'Kimya',
        'biology' => 'Biyoloji',
        'f_language_1' => '1. Yabancı Dil',
        'f_language_2' => '2. Yabancı Dil',
    ];

    $_lectures = [
        'math' => [
            'Sıralama ve Seçme',
            'Basit Olayların Olasılıkları',
            'Fonksiyon Kavramı ve Gösterimi',
            'İki Fonksiyonun Bileşkesi ve Bir Fonksiyonun Tersi',
            'Polinom Kavramı ve Polinomlarla İşlemler',
            'Polinomların Çarpanlara Ayrılması',
            'İkinci Dereceden Bir Bilinmeyenli Denklemler',
            'Çokgenler',
            'Dörtgenler ve Özellikleri',
            'Özel Dörtgenler',
            'Katı Cisimler',
        ],
        'turkish_l_l' => [
            'Yazım Kuralları',
            'Noktalama İşaretleri',
            'İsim',
            'Sıfat',
            'Dinleme Türleri ve Etkili Dinlemenin İlkeleri',
            'Edat',
            'Bağlaç',
            'Ünlem',
            'Zamir',
            'Zarf',
            'Fiil',
            'CV / Öz Geçmiş',
            'İletişim ve Dil',
            'Hikaye',
            'Şiir',
            'Masal/Fabl',
            'Roman',
            'Tiyatro',
            'Biyografi / Otobiyografi',
        ],
        'history' => [
            'Tarih ve Zaman',
            'İnsanlığın İlk Dönemleri',
            'Orta Çağ’da Dünya',
            'İlk ve Orta Çağlarda Türk Dünyası',
            'İslam Medeniyetinin Doğuşu',
            'Türklerin İslamiyeti Kabulü',
            'İlk Türk İslam Devletleri',
        ],
        'religion' => [
            'Din Kültürü ve Ahlak Bilgisi',
        ],
        'geography' => [
            'Doğa ve İnsan Etkileşimi',
            'Coğrafyanın Bölümleri',
            'Coğrafyanın Tarihi Gelişimi',
            'Coğrafyanın İlkeleri',
            'Coğrafyanın Yararlandığı Bilim Dalları',
            'Dünya’nın Şekli ve Sonuçları',
            'Dünya’nın Günlük Hareketi ve Sonuçları',
            'Dünya’nın Yıllık Hareketi ve Sonuçları',
            'Paralel ve Meridyenler',
            'Koordinat Sistemi',
            'Mutlak ve Göreceli Konum',
            'Türkiye’nin Özel Konumu ve Sonuçları',
            'Türkiye’nin Matematik Konumu ve Sonuçları',
            'Harita Bilgisi',
            'İzohips Haritası',
            'Atmosfer',
            'Hava Durumu ve İklim',
            'Sıcaklık',
            'Basınç ve Rüzgarlar',
            'Nem ve Yağış',
            'Yeryüzündeki İklim Tipleri',
            'Türkiye’nin İklimini Etkileyen Faktörler',
            'Türkiye’de İklim Elemanları',
            'Türkiye’de Görülen İklim Tipleri',
            'Yerleşmelerin Gelişimi',
            'Yerleşme Doku Ve Tipleri',
            'Türkiye’de Yerleşmelerin Gelişimi ve Fonksiyonel Özellikleri',
            'Türkiye’den ve Dünya’dan Bölge türleri',
            'İnsanların Doğal Çevreyi Kullanma Biçimler',
        ],
        'physics' => [
            'Elektrik ve Manyetizma',
            'Basınç ve Kaldırma Kuvveti',
            'Dalgalar',
            'Optik'
        ],
        'chemistry' => [
            'Kimyanın Temel Kanunları ve Kimyasal Hesaplamalar',
            'Karışımlar',
            'Asitler, Bazlar ve Tuzlar',
            'Kimya Her Yerde'
        ],
        'biology' => [
            'Hücre Bölünmeleri',
            'Kalıtımın Genel İlkeleri',
            'Ekosistem Ekolojisi ve Güncel Çevre Sorunları'
        ],
        'f_language_1' => [
            'Studying Abroad',
            'My Environment',
            'Movies',
            'Human in Nature',
            'Inspirational People',
            'Bridging Cultures',
            'World Heritage',
            'Emergency and Health Problems',
            'Invitations and Celebrations',
            'Television and Social Media',
        ],
        'f_language_2' => [
            'Almanca',
            'Fransızca'
        ],
    ];

} elseif (session('user_class') == 11) {

    $lesson_zero=[
        'math' => 0,
        'turkish_l_l' => 0,
        'history' => 0,
        'religion' => 0,
        'geography' => 0,
        'physics' => 0,
        'chemistry' => 0,
        'biology' => 0,
        'f_language_1' => 0,
        'f_language_2' => 0,
    ];

    $_lessons = [
        'math' => 'Matematik',
        'turkish_l_l' => 'Türk Dili ve Edebiyatı',
        'history' => 'Tarih',
        'religion' => 'Din Kültürü ve Ahlak Bilgisi',
        'geography' => 'Coğrafya',
        'physics' => 'Fizik',
        'chemistry' => 'Kimya',
        'biology' => 'Biyoloji',
        'f_language_1' => '1. Yabancı Dil',
        'f_language_2' => '2. Yabancı Dil',
    ];

    $_lectures = [
        'math' => [
            'Yönlü Açılar',
            'Trigonometrik Fonksiyonlar',
            'Doğrunun Analitik İncelenmesi',
            'Fonksiyonlarla İlgili Uygulamalar',
            'İkinci Dereceden Fonksiyonlar ve Grafikleri',
            'Fonksiyonların Dönüşümleri',
            'İkinci Dereceden İki Bilinmeyenli Denklem Sistemleri',
            'İkinci Dereceden Bir Bilinmeyenli Eşitsizlikler ve Eşitsizlik Sistemleri',
            'Çemberin Temel Elemanları',
            'Çemberde Açılar',
            'Çemberde Teğet',
            'Dairenin Çevresi ve Alanı',
            'Katı Cisimler',
            'Koşullu Olasılık',
            'Deneysel ve Teorik Olasılık'
        ],
        'turkish_l_l' => [
            'Yazım Kuralları',
            'Noktalama İşaretleri',
            'İsim',
            'Sıfat',
            'Dinleme Türleri ve Etkili Dinlemenin İlkeleri',
            'Edat',
            'Bağlaç',
            'Ünlem',
            'Zamir',
            'Zarf',
            'Fiil',
            'CV / Öz Geçmiş',
            'İletişim ve Dil',
            'Hikaye',
            'Şiir',
            'Masal/Fabl',
            'Roman',
            'Tiyatro',
            'Biyografi / Otobiyografi',
        ],
        'history' => [
            'Tarih ve Zaman',
            'İnsanlığın İlk Dönemleri',
            'Orta Çağ’da Dünya',
            'İlk ve Orta Çağlarda Türk Dünyası',
            'İslam Medeniyetinin Doğuşu',
            'Türklerin İslamiyeti Kabulü',
            'İlk Türk İslam Devletleri',
        ],
        'religion' => [
            'Din Kültürü ve Ahlak Bilgisi',
        ],
        'geography' => [
            'Doğa ve İnsan Etkileşimi',
            'Coğrafyanın Bölümleri',
            'Coğrafyanın Tarihi Gelişimi',
            'Coğrafyanın İlkeleri',
            'Coğrafyanın Yararlandığı Bilim Dalları',
            'Dünya’nın Şekli ve Sonuçları',
            'Dünya’nın Günlük Hareketi ve Sonuçları',
            'Dünya’nın Yıllık Hareketi ve Sonuçları',
            'Paralel ve Meridyenler',
            'Koordinat Sistemi',
            'Mutlak ve Göreceli Konum',
            'Türkiye’nin Özel Konumu ve Sonuçları',
            'Türkiye’nin Matematik Konumu ve Sonuçları',
            'Harita Bilgisi',
            'İzohips Haritası',
            'Atmosfer',
            'Hava Durumu ve İklim',
            'Sıcaklık',
            'Basınç ve Rüzgarlar',
            'Nem ve Yağış',
            'Yeryüzündeki İklim Tipleri',
            'Türkiye’nin İklimini Etkileyen Faktörler',
            'Türkiye’de İklim Elemanları',
            'Türkiye’de Görülen İklim Tipleri',
            'Yerleşmelerin Gelişimi',
            'Yerleşme Doku Ve Tipleri',
            'Türkiye’de Yerleşmelerin Gelişimi ve Fonksiyonel Özellikleri',
            'Türkiye’den ve Dünya’dan Bölge türleri',
            'İnsanların Doğal Çevreyi Kullanma Biçimler',
        ],
        'physics' => [
            'Kuvvet ve Hareket',
            'Elektrik ve Manyetizma'
        ],
        'chemistry' => [
            'Modern Atom Teorisi',
            'Gazlar',
            'Sıvı Çözeltiler ve Çözünürlük',
            'Sıvı Çözeltiler ve Çözünürlük',
            'Kimyasal Tepkimelerde Hız',
            'Kimyasal Tepkimelerde Denge',
        ],
        'biology' => [
            'İnsan Fizyolojisi',
            'Komünite ve Popülasyon Ekolojisi',
        ],
        'f_language_1' => [
            'Studying Abroad',
            'My Environment',
            'Movies',
            'Human in Nature',
            'Inspirational People',
            'Bridging Cultures',
            'World Heritage',
            'Emergency and Health Problems',
            'Invitations and Celebrations',
            'Television and Social Media',
        ],
        'f_language_2' => [
            'Almanca',
            'Fransızca'
        ],
    ];

} elseif (session('user_class') == 12) {

    $lesson_zero=[
        'math' => 0,
        'turkish_l_l' => 0,
        'history' => 0,
        'religion' => 0,
        'geography' => 0,
        'physics' => 0,
        'chemistry' => 0,
        'biology' => 0,
        'f_language_1' => 0,
        'f_language_2' => 0,
    ];

    $_lessons = [
        'math' => 'Matematik',
        'turkish_l_l' => 'Türk Dili ve Edebiyatı',
        'history' => 'Tarih',
        'religion' => 'Din Kültürü ve Ahlak Bilgisi',
        'geography' => 'Coğrafya',
        'physics' => 'Fizik',
        'chemistry' => 'Kimya',
        'biology' => 'Biyoloji',
        'f_language_1' => '1. Yabancı Dil',
        'f_language_2' => '2. Yabancı Dil',
    ];

    $_lectures = [
        'math' => [
            'Üstel Fonksiyon',
            'Logaritma Fonksiyonu',
            'Üstel, Logaritmik Denklemler ve Eşitsizlikler',
            'Gerçek Sayı Dizileri',
            'Toplam-Fark ve İki Kat Açı Formülleri',
            'Trigonometrik Denklemler',
            'Analitik Düzlemde Temel Dönüşümler',
            'Limit ve Süreklili',
            'Anlık Değişim Oranı ve Türev',
            'Türevin Uygulamaları',
            'Belirsiz İntegral',
            'Belirli İntegral ve Uygulamaları',
            'Çemberin Analitik İncelenmesi',
        ],
        'turkish_l_l' => [
            'Yazım Kuralları',
            'Noktalama İşaretleri',
            'İsim',
            'Sıfat',
            'Dinleme Türleri ve Etkili Dinlemenin İlkeleri',
            'Edat',
            'Bağlaç',
            'Ünlem',
            'Zamir',
            'Zarf',
            'Fiil',
            'CV / Öz Geçmiş',
            'İletişim ve Dil',
            'Hikaye',
            'Şiir',
            'Masal/Fabl',
            'Roman',
            'Tiyatro',
            'Biyografi / Otobiyografi',
        ],
        'history' => [
            'Tarih ve Zaman',
            'İnsanlığın İlk Dönemleri',
            'Orta Çağ’da Dünya',
            'İlk ve Orta Çağlarda Türk Dünyası',
            'İslam Medeniyetinin Doğuşu',
            'Türklerin İslamiyeti Kabulü',
            'İlk Türk İslam Devletleri',
        ],
        'religion' => [
            'Din Kültürü ve Ahlak Bilgisi',
        ],
        'geography' => [
            'Doğa ve İnsan Etkileşimi',
            'Coğrafyanın Bölümleri',
            'Coğrafyanın Tarihi Gelişimi',
            'Coğrafyanın İlkeleri',
            'Coğrafyanın Yararlandığı Bilim Dalları',
            'Dünya’nın Şekli ve Sonuçları',
            'Dünya’nın Günlük Hareketi ve Sonuçları',
            'Dünya’nın Yıllık Hareketi ve Sonuçları',
            'Paralel ve Meridyenler',
            'Koordinat Sistemi',
            'Mutlak ve Göreceli Konum',
            'Türkiye’nin Özel Konumu ve Sonuçları',
            'Türkiye’nin Matematik Konumu ve Sonuçları',
            'Harita Bilgisi',
            'İzohips Haritası',
            'Atmosfer',
            'Hava Durumu ve İklim',
            'Sıcaklık',
            'Basınç ve Rüzgarlar',
            'Nem ve Yağış',
            'Yeryüzündeki İklim Tipleri',
            'Türkiye’nin İklimini Etkileyen Faktörler',
            'Türkiye’de İklim Elemanları',
            'Türkiye’de Görülen İklim Tipleri',
            'Yerleşmelerin Gelişimi',
            'Yerleşme Doku Ve Tipleri',
            'Türkiye’de Yerleşmelerin Gelişimi ve Fonksiyonel Özellikleri',
            'Türkiye’den ve Dünya’dan Bölge türleri',
            'İnsanların Doğal Çevreyi Kullanma Biçimler',
        ],
        'physics' => [
            'Çembersel Hareket',
            'Basit Harmonik Hareket',
            'Dalga Mekaniği',
            'Atom Fiziğine Giriş ve Radyoaktivite',
            'Modern Fizik',
            'Modern Fiziğin Teknolojideki Uygulamaları'
        ],
        'chemistry' => [
            'Kimya ve Elektrik',
            'Karbon Kimyasına Giriş',
            'Kimyacıların Çalışma Alanları',
            'Organik Bileşikler',
            'Enerji Kaynakları ve Bilimsel Gelişmeler',
        ],
        'biology' => [
            'Genden Proteine',
            'Canlılarda Enerji Dönüşümleri',
            'Bitki Biyolojisi',
            'Canlılar ve Çevre'
        ],
        'f_language_1' => [
            'Studying Abroad',
            'My Environment',
            'Movies',
            'Human in Nature',
            'Inspirational People',
            'Bridging Cultures',
            'World Heritage',
            'Emergency and Health Problems',
            'Invitations and Celebrations',
            'Television and Social Media',
        ],
        'f_language_2' => [
            'Almanca',
            'Fransızca'
        ],
    ];

} elseif (session('user_class') == 50) {

    $lesson_zero=[
        'math' => 0,
        'turkish_l_l' => 0,
        'history' => 0,
        'religion' => 0,
        'geography' => 0,
        'physics' => 0,
        'chemistry' => 0,
        'biology' => 0,
        'f_language_1' => 0,
        'f_language_2' => 0,
    ];

    $_lessons = [
        'math' => 'Matematik',
        'turkish_l_l' => 'Türk Dili ve Edebiyatı',
        'history' => 'Tarih',
        'religion' => 'Din Kültürü ve Ahlak Bilgisi',
        'geography' => 'Coğrafya',
        'physics' => 'Fizik',
        'chemistry' => 'Kimya',
        'biology' => 'Biyoloji',
        'f_language_1' => '1. Yabancı Dil',
        'f_language_2' => '2. Yabancı Dil',
    ];

    $_lectures = [
        'math' => [
            'Önermeler ve Bileşik Önermeler',
            'Açık Önermeler ve İspat Teknikleri',
            'Kümelerde Temel Kavramlar',
            'Kümelerde İşlemler ve Bağıntı',
            'Sayı Kümeleri',
            'Bölünebilme Kuralları',
            'Birinci Dereceden Denklemler ve Eşitsizlikler',
            'Üslü İfadeler ve Denklemler',
            'Denklemler ve Eşitsizliklerle İlgili Uygulamalar',
            'Üçgenlerde Temel Kavramlar',
            'Üçgenlerde Eşlik ve Benzerlik',
            'Üçgenlerin Yardımcı Elemanları',
            'Dik Üçgen ve Trigonometri',
            'Üçgenin Alanı',
            'Merkezî Eğilim ve Yayılım Ölçüleri',
            'Verilerin Grafikle Gösterilmesi',
        ],
        'turkish_l_l' => [
            'Yazım Kuralları',
            'Noktalama İşaretleri',
            'İsim',
            'Sıfat',
            'Dinleme Türleri ve Etkili Dinlemenin İlkeleri',
            'Edat',
            'Bağlaç',
            'Ünlem',
            'Zamir',
            'Zarf',
            'Fiil',
            'CV / Öz Geçmiş',
            'İletişim ve Dil',
            'Hikaye',
            'Şiir',
            'Masal/Fabl',
            'Roman',
            'Tiyatro',
            'Biyografi / Otobiyografi',
        ],
        'history' => [
            'Tarih ve Zaman',
            'İnsanlığın İlk Dönemleri',
            'Orta Çağ’da Dünya',
            'İlk ve Orta Çağlarda Türk Dünyası',
            'İslam Medeniyetinin Doğuşu',
            'Türklerin İslamiyeti Kabulü',
            'İlk Türk İslam Devletleri',
        ],
        'religion' => [
            'Din Kültürü ve Ahlak Bilgisi',
        ],
        'geography' => [
            'Doğa ve İnsan Etkileşimi',
            'Coğrafyanın Bölümleri',
            'Coğrafyanın Tarihi Gelişimi',
            'Coğrafyanın İlkeleri',
            'Coğrafyanın Yararlandığı Bilim Dalları',
            'Dünya’nın Şekli ve Sonuçları',
            'Dünya’nın Günlük Hareketi ve Sonuçları',
            'Dünya’nın Yıllık Hareketi ve Sonuçları',
            'Paralel ve Meridyenler',
            'Koordinat Sistemi',
            'Mutlak ve Göreceli Konum',
            'Türkiye’nin Özel Konumu ve Sonuçları',
            'Türkiye’nin Matematik Konumu ve Sonuçları',
            'Harita Bilgisi',
            'İzohips Haritası',
            'Atmosfer',
            'Hava Durumu ve İklim',
            'Sıcaklık',
            'Basınç ve Rüzgarlar',
            'Nem ve Yağış',
            'Yeryüzündeki İklim Tipleri',
            'Türkiye’nin İklimini Etkileyen Faktörler',
            'Türkiye’de İklim Elemanları',
            'Türkiye’de Görülen İklim Tipleri',
            'Yerleşmelerin Gelişimi',
            'Yerleşme Doku Ve Tipleri',
            'Türkiye’de Yerleşmelerin Gelişimi ve Fonksiyonel Özellikleri',
            'Türkiye’den ve Dünya’dan Bölge türleri',
            'İnsanların Doğal Çevreyi Kullanma Biçimler',
        ],
        'physics' => [
            'Fizik Bilimine Giriş',
            'Madde ve Özellikleri',
            'Hareket ve Kuvvet',
            'Enerji',
            'Isı ve Sıcaklık',
            'Elektrostatik',
        ],
        'chemistry' => [
            'Simyadan Kimya',
            'Kimya Disiplinleri',
            'Kimyacıların Çalışma Alanları',
            'Kimyanın Sembolik Dili',
            'Kimya Uygulamalarında İş Sağlığı ve Güvenliği',
            'Atom Modelleri',
            'Atomun Yapısı',
            'Periyodik Sitem',
            'Kimyasal Tür',
            'Güçlü Etkileşimler',
            'Zayıf Etkileşimler',
            'Fiziksel ve Kimyasal Değişimler',
            'Maddenin Fiziksel Halleri',
            'Katılar',
            'Sıvılar',
            'Gazlar',
            'Plazma',
            'Su ve Hayat',
            'Çevre Kimyası',
        ],
        'biology' => [
            'Biyoloji ve Canlıların Ortak Özellikleri',
            'Canlıların Yapısında Bulunan Temel Bileşikler',
            'Hücre',
            'Canlıların Çeşitliliği ve Sınıflandırılması',
            'Canlı Alemleri ve Özellikleri',
        ],
        'f_language_1' => [
            'Studying Abroad',
            'My Environment',
            'Movies',
            'Human in Nature',
            'Inspirational People',
            'Bridging Cultures',
            'World Heritage',
            'Emergency and Health Problems',
            'Invitations and Celebrations',
            'Television and Social Media',
        ],
        'f_language_2' => [
            'Almanca',
            'Fransızca'
        ],
    ];

} elseif (session('user_class') == 51) {

    $lesson_zero=[
        'math' => 0,
        'turkish_l_l' => 0,
        'history' => 0,
        'religion' => 0,
        'geography' => 0,
        'physics' => 0,
        'chemistry' => 0,
        'biology' => 0,
        'f_language_1' => 0,
        'f_language_2' => 0,
    ];

    $_lessons = [
        'math' => 'Matematik',
        'turkish_l_l' => 'Türk Dili ve Edebiyatı',
        'history' => 'Tarih',
        'religion' => 'Din Kültürü ve Ahlak Bilgisi',
        'geography' => 'Coğrafya',
        'physics' => 'Fizik',
        'chemistry' => 'Kimya',
        'biology' => 'Biyoloji',
        'f_language_1' => '1. Yabancı Dil',
        'f_language_2' => '2. Yabancı Dil',
    ];

    $_lectures = [
        'math' => [
            'Sıralama ve Seçme',
            'Basit Olayların Olasılıkları',
            'Fonksiyon Kavramı ve Gösterimi',
            'İki Fonksiyonun Bileşkesi ve Bir Fonksiyonun Tersi',
            'Polinom Kavramı ve Polinomlarla İşlemler',
            'Polinomların Çarpanlara Ayrılması',
            'İkinci Dereceden Bir Bilinmeyenli Denklemler',
            'Çokgenler',
            'Dörtgenler ve Özellikleri',
            'Özel Dörtgenler',
            'Katı Cisimler',
        ],
        'turkish_l_l' => [
            'Yazım Kuralları',
            'Noktalama İşaretleri',
            'İsim',
            'Sıfat',
            'Dinleme Türleri ve Etkili Dinlemenin İlkeleri',
            'Edat',
            'Bağlaç',
            'Ünlem',
            'Zamir',
            'Zarf',
            'Fiil',
            'CV / Öz Geçmiş',
            'İletişim ve Dil',
            'Hikaye',
            'Şiir',
            'Masal/Fabl',
            'Roman',
            'Tiyatro',
            'Biyografi / Otobiyografi',
        ],
        'history' => [
            'Tarih ve Zaman',
            'İnsanlığın İlk Dönemleri',
            'Orta Çağ’da Dünya',
            'İlk ve Orta Çağlarda Türk Dünyası',
            'İslam Medeniyetinin Doğuşu',
            'Türklerin İslamiyeti Kabulü',
            'İlk Türk İslam Devletleri',
        ],
        'religion' => [
            'Din Kültürü ve Ahlak Bilgisi',
        ],
        'geography' => [
            'Doğa ve İnsan Etkileşimi',
            'Coğrafyanın Bölümleri',
            'Coğrafyanın Tarihi Gelişimi',
            'Coğrafyanın İlkeleri',
            'Coğrafyanın Yararlandığı Bilim Dalları',
            'Dünya’nın Şekli ve Sonuçları',
            'Dünya’nın Günlük Hareketi ve Sonuçları',
            'Dünya’nın Yıllık Hareketi ve Sonuçları',
            'Paralel ve Meridyenler',
            'Koordinat Sistemi',
            'Mutlak ve Göreceli Konum',
            'Türkiye’nin Özel Konumu ve Sonuçları',
            'Türkiye’nin Matematik Konumu ve Sonuçları',
            'Harita Bilgisi',
            'İzohips Haritası',
            'Atmosfer',
            'Hava Durumu ve İklim',
            'Sıcaklık',
            'Basınç ve Rüzgarlar',
            'Nem ve Yağış',
            'Yeryüzündeki İklim Tipleri',
            'Türkiye’nin İklimini Etkileyen Faktörler',
            'Türkiye’de İklim Elemanları',
            'Türkiye’de Görülen İklim Tipleri',
            'Yerleşmelerin Gelişimi',
            'Yerleşme Doku Ve Tipleri',
            'Türkiye’de Yerleşmelerin Gelişimi ve Fonksiyonel Özellikleri',
            'Türkiye’den ve Dünya’dan Bölge türleri',
            'İnsanların Doğal Çevreyi Kullanma Biçimler',
        ],
        'physics' => [
            'Elektrik ve Manyetizma',
            'Basınç ve Kaldırma Kuvveti',
            'Dalgalar',
            'Optik'
        ],
        'chemistry' => [
            'Kimyanın Temel Kanunları ve Kimyasal Hesaplamalar',
            'Karışımlar',
            'Asitler, Bazlar ve Tuzlar',
            'Kimya Her Yerde'
        ],
        'biology' => [
            'Hücre Bölünmeleri',
            'Kalıtımın Genel İlkeleri',
            'Ekosistem Ekolojisi ve Güncel Çevre Sorunları'
        ],
        'f_language_1' => [
            'Studying Abroad',
            'My Environment',
            'Movies',
            'Human in Nature',
            'Inspirational People',
            'Bridging Cultures',
            'World Heritage',
            'Emergency and Health Problems',
            'Invitations and Celebrations',
            'Television and Social Media',
        ],
        'f_language_2' => [
            'Almanca',
            'Fransızca'
        ],
    ];

} elseif (session('user_class') == 52) {

    $lesson_zero=[
        'math' => 0,
        'turkish_l_l' => 0,
        'history' => 0,
        'religion' => 0,
        'geography' => 0,
        'physics' => 0,
        'chemistry' => 0,
        'biology' => 0,
        'f_language_1' => 0,
        'f_language_2' => 0,
    ];

    $_lessons = [
        'math' => 'Matematik',
        'turkish_l_l' => 'Türk Dili ve Edebiyatı',
        'history' => 'Tarih',
        'religion' => 'Din Kültürü ve Ahlak Bilgisi',
        'geography' => 'Coğrafya',
        'physics' => 'Fizik',
        'chemistry' => 'Kimya',
        'biology' => 'Biyoloji',
        'f_language_1' => '1. Yabancı Dil',
        'f_language_2' => '2. Yabancı Dil',
    ];

    $_lectures = [
        'math' => [
            'Yönlü Açılar',
            'Trigonometrik Fonksiyonlar',
            'Doğrunun Analitik İncelenmesi',
            'Fonksiyonlarla İlgili Uygulamalar',
            'İkinci Dereceden Fonksiyonlar ve Grafikleri',
            'Fonksiyonların Dönüşümleri',
            'İkinci Dereceden İki Bilinmeyenli Denklem Sistemleri',
            'İkinci Dereceden Bir Bilinmeyenli Eşitsizlikler ve Eşitsizlik Sistemleri',
            'Çemberin Temel Elemanları',
            'Çemberde Açılar',
            'Çemberde Teğet',
            'Dairenin Çevresi ve Alanı',
            'Katı Cisimler',
            'Koşullu Olasılık',
            'Deneysel ve Teorik Olasılık'
        ],
        'turkish_l_l' => [
            'Yazım Kuralları',
            'Noktalama İşaretleri',
            'İsim',
            'Sıfat',
            'Dinleme Türleri ve Etkili Dinlemenin İlkeleri',
            'Edat',
            'Bağlaç',
            'Ünlem',
            'Zamir',
            'Zarf',
            'Fiil',
            'CV / Öz Geçmiş',
            'İletişim ve Dil',
            'Hikaye',
            'Şiir',
            'Masal/Fabl',
            'Roman',
            'Tiyatro',
            'Biyografi / Otobiyografi',
        ],
        'history' => [
            'Tarih ve Zaman',
            'İnsanlığın İlk Dönemleri',
            'Orta Çağ’da Dünya',
            'İlk ve Orta Çağlarda Türk Dünyası',
            'İslam Medeniyetinin Doğuşu',
            'Türklerin İslamiyeti Kabulü',
            'İlk Türk İslam Devletleri',
        ],
        'religion' => [
            'Din Kültürü ve Ahlak Bilgisi',
        ],
        'geography' => [
            'Doğa ve İnsan Etkileşimi',
            'Coğrafyanın Bölümleri',
            'Coğrafyanın Tarihi Gelişimi',
            'Coğrafyanın İlkeleri',
            'Coğrafyanın Yararlandığı Bilim Dalları',
            'Dünya’nın Şekli ve Sonuçları',
            'Dünya’nın Günlük Hareketi ve Sonuçları',
            'Dünya’nın Yıllık Hareketi ve Sonuçları',
            'Paralel ve Meridyenler',
            'Koordinat Sistemi',
            'Mutlak ve Göreceli Konum',
            'Türkiye’nin Özel Konumu ve Sonuçları',
            'Türkiye’nin Matematik Konumu ve Sonuçları',
            'Harita Bilgisi',
            'İzohips Haritası',
            'Atmosfer',
            'Hava Durumu ve İklim',
            'Sıcaklık',
            'Basınç ve Rüzgarlar',
            'Nem ve Yağış',
            'Yeryüzündeki İklim Tipleri',
            'Türkiye’nin İklimini Etkileyen Faktörler',
            'Türkiye’de İklim Elemanları',
            'Türkiye’de Görülen İklim Tipleri',
            'Yerleşmelerin Gelişimi',
            'Yerleşme Doku Ve Tipleri',
            'Türkiye’de Yerleşmelerin Gelişimi ve Fonksiyonel Özellikleri',
            'Türkiye’den ve Dünya’dan Bölge türleri',
            'İnsanların Doğal Çevreyi Kullanma Biçimler',
        ],
        'physics' => [
            'Kuvvet ve Hareket',
            'Elektrik ve Manyetizma'
        ],
        'chemistry' => [
            'Modern Atom Teorisi',
            'Gazlar',
            'Sıvı Çözeltiler ve Çözünürlük',
            'Sıvı Çözeltiler ve Çözünürlük',
            'Kimyasal Tepkimelerde Hız',
            'Kimyasal Tepkimelerde Denge',
        ],
        'biology' => [
            'İnsan Fizyolojisi',
            'Komünite ve Popülasyon Ekolojisi',
        ],
        'f_language_1' => [
            'Studying Abroad',
            'My Environment',
            'Movies',
            'Human in Nature',
            'Inspirational People',
            'Bridging Cultures',
            'World Heritage',
            'Emergency and Health Problems',
            'Invitations and Celebrations',
            'Television and Social Media',
        ],
        'f_language_2' => [
            'Almanca',
            'Fransızca'
        ],
    ];

} elseif (session('user_class') == 53) {

    $lesson_zero=[
        'math' => 0,
        'turkish_l_l' => 0,
        'history' => 0,
        'religion' => 0,
        'geography' => 0,
        'physics' => 0,
        'chemistry' => 0,
        'biology' => 0,
        'f_language_1' => 0,
        'f_language_2' => 0,
    ];

    $_lessons = [
        'math' => 'Matematik',
        'turkish_l_l' => 'Türk Dili ve Edebiyatı',
        'history' => 'Tarih',
        'religion' => 'Din Kültürü ve Ahlak Bilgisi',
        'geography' => 'Coğrafya',
        'physics' => 'Fizik',
        'chemistry' => 'Kimya',
        'biology' => 'Biyoloji',
        'f_language_1' => '1. Yabancı Dil',
        'f_language_2' => '2. Yabancı Dil',
    ];

    $_lectures = [
        'math' => [
            'Üstel Fonksiyon',
            'Logaritma Fonksiyonu',
            'Üstel, Logaritmik Denklemler ve Eşitsizlikler',
            'Gerçek Sayı Dizileri',
            'Toplam-Fark ve İki Kat Açı Formülleri',
            'Trigonometrik Denklemler',
            'Analitik Düzlemde Temel Dönüşümler',
            'Limit ve Süreklili',
            'Anlık Değişim Oranı ve Türev',
            'Türevin Uygulamaları',
            'Belirsiz İntegral',
            'Belirli İntegral ve Uygulamaları',
            'Çemberin Analitik İncelenmesi',
        ],
        'turkish_l_l' => [
            'Yazım Kuralları',
            'Noktalama İşaretleri',
            'İsim',
            'Sıfat',
            'Dinleme Türleri ve Etkili Dinlemenin İlkeleri',
            'Edat',
            'Bağlaç',
            'Ünlem',
            'Zamir',
            'Zarf',
            'Fiil',
            'CV / Öz Geçmiş',
            'İletişim ve Dil',
            'Hikaye',
            'Şiir',
            'Masal/Fabl',
            'Roman',
            'Tiyatro',
            'Biyografi / Otobiyografi',
        ],
        'history' => [
            'Tarih ve Zaman',
            'İnsanlığın İlk Dönemleri',
            'Orta Çağ’da Dünya',
            'İlk ve Orta Çağlarda Türk Dünyası',
            'İslam Medeniyetinin Doğuşu',
            'Türklerin İslamiyeti Kabulü',
            'İlk Türk İslam Devletleri',
        ],
        'religion' => [
            'Din Kültürü ve Ahlak Bilgisi',
        ],
        'geography' => [
            'Doğa ve İnsan Etkileşimi',
            'Coğrafyanın Bölümleri',
            'Coğrafyanın Tarihi Gelişimi',
            'Coğrafyanın İlkeleri',
            'Coğrafyanın Yararlandığı Bilim Dalları',
            'Dünya’nın Şekli ve Sonuçları',
            'Dünya’nın Günlük Hareketi ve Sonuçları',
            'Dünya’nın Yıllık Hareketi ve Sonuçları',
            'Paralel ve Meridyenler',
            'Koordinat Sistemi',
            'Mutlak ve Göreceli Konum',
            'Türkiye’nin Özel Konumu ve Sonuçları',
            'Türkiye’nin Matematik Konumu ve Sonuçları',
            'Harita Bilgisi',
            'İzohips Haritası',
            'Atmosfer',
            'Hava Durumu ve İklim',
            'Sıcaklık',
            'Basınç ve Rüzgarlar',
            'Nem ve Yağış',
            'Yeryüzündeki İklim Tipleri',
            'Türkiye’nin İklimini Etkileyen Faktörler',
            'Türkiye’de İklim Elemanları',
            'Türkiye’de Görülen İklim Tipleri',
            'Yerleşmelerin Gelişimi',
            'Yerleşme Doku Ve Tipleri',
            'Türkiye’de Yerleşmelerin Gelişimi ve Fonksiyonel Özellikleri',
            'Türkiye’den ve Dünya’dan Bölge türleri',
            'İnsanların Doğal Çevreyi Kullanma Biçimler',
        ],
        'physics' => [
            'Çembersel Hareket',
            'Basit Harmonik Hareket',
            'Dalga Mekaniği',
            'Atom Fiziğine Giriş ve Radyoaktivite',
            'Modern Fizik',
            'Modern Fiziğin Teknolojideki Uygulamaları'
        ],
        'chemistry' => [
            'Kimya ve Elektrik',
            'Karbon Kimyasına Giriş',
            'Kimyacıların Çalışma Alanları',
            'Organik Bileşikler',
            'Enerji Kaynakları ve Bilimsel Gelişmeler',
        ],
        'biology' => [
            'Genden Proteine',
            'Canlılarda Enerji Dönüşümleri',
            'Bitki Biyolojisi',
            'Canlılar ve Çevre'
        ],
        'f_language_1' => [
            'Studying Abroad',
            'My Environment',
            'Movies',
            'Human in Nature',
            'Inspirational People',
            'Bridging Cultures',
            'World Heritage',
            'Emergency and Health Problems',
            'Invitations and Celebrations',
            'Television and Social Media',
        ],
        'f_language_2' => [
            'Almanca',
            'Fransızca'
        ],
    ];

} elseif (session('user_class') == 80){

    $lesson_zero=[
        'math' => 0,
        'geometry' => 0,
        'turkish' => 0,
        'history' => 0,
        'geography' => 0,
        'citizenship' => 0,
    ];

    $_lessons = [
        'math' => 'Matematik',
        'geometry' => 'Geometri',
        'turkish' => 'Türkçe',
        'history' => 'Tarih',
        'geography' => 'Coğrafya',
        'citizenship' => 'Vatandaşlık',
    ];

    $_lectures = [

        'math' => [
            'Temel Kavramlar',
            'Sayılar',
            'Bölme-Bölünebilme Kuralları',
            'Asal Çarpanlara Ayırma',
            'EBOB-EKOK',
            'Birinci Dereceden Denklemler',
            'Rasyonel Sayılar',
            'Eşitsizlikler',
            'Mutlak Değer',
            'Üslü Sayılar',
            'Köklü Sayılar',
            'Çarpanlara Ayırma',
            'Oran – Orantı',
            'Problemler',
            'Kümeler',
            'Fonskiyon İşlem',
            'Modüler Aritmetik ',
            'Permütasyon – Kombinasyon – Olasılık',
            'Tablo ve Grafikler',
            'Sayısal Mantık',
        ],
        'geometry' => [
            'Geometrik Kavramlar',
            'Doğruda Açılar',
            'Üçgende Açılar',
            'Üçgende Alan',
            'Üçgende Benzerlik',
            'Açı Kenar Bağıntıları',
            'Özel Üçgenler',
            'Açıortay',
            'Kenarortay',
            'Çokgenler',
            'Dörtgenler',
            'Çember ve Daire',
            'Analitik Geometri',
            'Katı Cisimler',
        ],
        'turkish' => [
            'Sözcükte Anlam',
            'Cümlede Anlam',
            'Paragrafta Anlam',
            'Ses Bilgisi',
            'Yapı Bilgisi',
            'Sözcük Türleri',
            'Cümle Bilgisi',
            'Yazım Kuralları',
            'Noktalama İşaretleri',
            'Anlatım Bozuklukları',
            'Sözel Mantık',
        ],
        'history' => [
            'İslamiyet Öncesi Türk Tarihi',
            'Türk-İslam Tarihi',
            'Osmanlı Tarihi',
            'Osmanlı Yenileşme ve Demokratikleşme Hareketleri',
            'Avrupa’da Yaşanan Gelişmeler ve Türk-İslam Dünyasına Etkileri',
            'XX.Yüzyılda Osmanlı Devleti',
            'Kurtuluş Savaşı Hazırlık Dönemi',
            'Kurtuluş Savaşı Muharebeler ve Antlaşmalar Dönemi',
            'Cumhuriyet Dönemi',
            'Atatürk Dönemi Türk Dış Politikası',
            'Çağdaş Türk ve Dünya Tarihi',
        ],
        'geography' => [
            'Türkiye’nin Coğrafi Konumu',
            'Türkiye’nin Yer Şekilleri ve Özellikleri',
            'Türkiye’nin İklimi ve Bitki Örtüsü',
            'Türkiye’de Nüfus ve Yerleşme',
            'Türkiye’de Tarım, Hayvancılık ve Ormancılık',
            'Türkiye’de Madenler, Enerji Kaynakları ve Sanayi',
            'Türkiye’de Ulaşım, Turizm ve Ticaret',
            'Türkiye’nin Bölgesel Coğrafyası',
        ],
        'citizenship' => [
            'Hukukun Temel Kavramları',
            'Devlet Biçimleri Demokrasi ve Kuvvetler Ayrılığı',
            'Anayasa Hukukuna Giriş, Temel Kavramlar ve Türk Anayasa Tarihi',
            '1982 Anayasası’nın Temel İlkeleri',
            'Temel Hak ve Hürriyetler',
            'Yasama',
            'Yürütme',
            'Yargı',
            'İdare Hukuku',
        ]

    ];

} elseif (session('user_class') == 81){

    $lesson_zero=[
        'math' => 0,
        'geometry' => 0,
        'turkish' => 0,
        'history' => 0,
        'geography' => 0,
        'citizenship' => 0,
        'developmental_psychology' => 0,
        'learning_psychology' => 0,
        'program_development' => 0,
        'guidance' => 0,
        'measurement_and_evaluation' => 0,
        'teaching_principles_and_methods' => 0,
    ];

    $_lessons = [
        'math' => 'Matematik',
        'geometry' => 'Geometri',
        'turkish' => 'Türkçe',
        'history' => 'Tarih',
        'geography' => 'Coğrafya',
        'citizenship' => 'Vatandaşlık',
        'developmental_psychology' => 'Gelişim Psikolojisi',
        'learning_psychology' => 'Öğrenme Psikolojisi',
        'program_development' => 'Program Geliştirme',
        'guidance' => 'Rehberlik',
        'measurement_and_evaluation' => 'Ölçme ve Değerlendirme',
        'teaching_principles_and_methods' => 'Öğretim İlke ve Yöntemleri',

    ];

    $_lectures = [

        'math' => [
            'Temel Kavramlar',
            'Sayılar',
            'Bölme-Bölünebilme Kuralları',
            'Asal Çarpanlara Ayırma',
            'EBOB-EKOK',
            'Birinci Dereceden Denklemler',
            'Rasyonel Sayılar',
            'Eşitsizlikler',
            'Mutlak Değer',
            'Üslü Sayılar',
            'Köklü Sayılar',
            'Çarpanlara Ayırma',
            'Oran – Orantı',
            'Problemler',
            'Kümeler',
            'Fonskiyon İşlem',
            'Modüler Aritmetik ',
            'Permütasyon – Kombinasyon – Olasılık',
            'Tablo ve Grafikler',
            'Sayısal Mantık',
        ],
        'geometry' => [
            'Geometrik Kavramlar',
            'Doğruda Açılar',
            'Üçgende Açılar',
            'Üçgende Alan',
            'Üçgende Benzerlik',
            'Açı Kenar Bağıntıları',
            'Özel Üçgenler',
            'Açıortay',
            'Kenarortay',
            'Çokgenler',
            'Dörtgenler',
            'Çember ve Daire',
            'Analitik Geometri',
            'Katı Cisimler',
        ],
        'turkish' => [
            'Sözcükte Anlam',
            'Cümlede Anlam',
            'Paragrafta Anlam',
            'Ses Bilgisi',
            'Yapı Bilgisi',
            'Sözcük Türleri',
            'Cümle Bilgisi',
            'Yazım Kuralları',
            'Noktalama İşaretleri',
            'Anlatım Bozuklukları',
            'Sözel Mantık',
        ],
        'history' => [
            'İslamiyet Öncesi Türk Tarihi',
            'Türk-İslam Tarihi',
            'Osmanlı Tarihi',
            'Osmanlı Yenileşme ve Demokratikleşme Hareketleri',
            'Avrupa’da Yaşanan Gelişmeler ve Türk-İslam Dünyasına Etkileri',
            'XX.Yüzyılda Osmanlı Devleti',
            'Kurtuluş Savaşı Hazırlık Dönemi',
            'Kurtuluş Savaşı Muharebeler ve Antlaşmalar Dönemi',
            'Cumhuriyet Dönemi',
            'Atatürk Dönemi Türk Dış Politikası',
            'Çağdaş Türk ve Dünya Tarihi',
        ],
        'geography' => [
            'Türkiye’nin Coğrafi Konumu',
            'Türkiye’nin Yer Şekilleri ve Özellikleri',
            'Türkiye’nin İklimi ve Bitki Örtüsü',
            'Türkiye’de Nüfus ve Yerleşme',
            'Türkiye’de Tarım, Hayvancılık ve Ormancılık',
            'Türkiye’de Madenler, Enerji Kaynakları ve Sanayi',
            'Türkiye’de Ulaşım, Turizm ve Ticaret',
            'Türkiye’nin Bölgesel Coğrafyası',
        ],
        'citizenship' => [
            'Hukukun Temel Kavramları',
            'Devlet Biçimleri Demokrasi ve Kuvvetler Ayrılığı',
            'Anayasa Hukukuna Giriş, Temel Kavramlar ve Türk Anayasa Tarihi',
            '1982 Anayasası’nın Temel İlkeleri',
            'Temel Hak ve Hürriyetler',
            'Yasama',
            'Yürütme',
            'Yargı',
            'İdare Hukuku',
        ],
        'developmental_psychology' => [
            'Gelişim Psikolojisi',
            'Biyolojik Gelişim',
            'Bilişsel Gelişim',
            'Ahlâk Gelişimi',
            'Kişilik Gelişimi',
        ],
        'learning_psychology' => [
            'Öğrenme Psikolojisine Giriş',
            'Klasik Koşullanma',
            'Bağlaşımcılık Kuramı',
            'Bitişiklik Kuramı',
            'Edimsel Koşullanma Kuramı',
            'Gestalt Kuramı',
            'Bilgi İşleme Kuramı',
            'İşaret - Gestalt Kuramı',
            'Sosyal Öğrenme Kuramı',
        ],
        'program_development' => [
            'Eğitim İle İlgili Temel Kavramlar',
            'Türk Eğitim Sistemi',
            'Eğitimde Program Kavramı ve Program Türleri',
            'Program Geliştirme ve Program Geliştirmenin Kuramsal Temelleri',
            'Program Geliştirme Yaklaşım, Model ve Tasarımları',
            'Program Tasarısının Hazırlanması',
            'Programın Denenmesi Değerlendirilmesi Programa Süreklilik Kazandırılması',
            'Program Geliştirmede Yeni Anlayışlar ve Yönelimler',
            'Eğitim Öğretimde Planlama',
        ],
        'guidance' => [
            'Ölçme ve Değerlendirmede Temel Kavramlar',
            'Ölçme Araçlarında Bulunması Gereken Nitelikler',
            'Eğitimde Kullanılan Ölçme Araçları',
            'Test ve Madde İstatistikleri',
        ],
        'measurement_and_evaluation' => [
            'Eğitimle İlgili Temel Kavramlar, Öğretim İlkeleri ve Öğretim Stratejileri',
            'Öğretme-Öğrenme Yaklaşımları (Modelleri-Kuramları)',
            'Öğretim Yöntemleri',
            'Öğretim Teknikleri',
            'Kavram Öğretimi',
            'Öğrenme Stratejileri',
            'Öğrenme Stilleri ve Üst Düzey Zihinsel Beceriler',

        ],
        'teaching_principles_and_methods' => [
            'Çağdaş Eğitim Anlayışı, Öğrenci Kişilik Hizmetleri ve Rehberlik Hizmetleri',
            'Özel Eğitim Hizmetleri',
            'Rehberlik Hizmet Alanları',
            'Rehberlik Türleri ve Mesleki Danışma Kuramları',
            'Bireyi Tanıma Teknikleri',
            'Psikolojik Danışma Kuramları',
            'Okullarda Karşılaşılabilecek Bazı Sorunlar',
            'Rehberlik Örgütlenme Sistemi',
        ],


    ];
}















